apiVersion: v1
kind: Pod
metadata: 
  name: java12
spec: 
 containers: 
   - name: java12
     image: nginx
     env: 
      - name: password 
        valueFrom: 
          secretKeyRef: 
              name:  java 
              key: password 