apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
 name: java12
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      color: red 
  template: 
    metadata: 
      name: javapod
      labels: 
        color: red
    spec: 
      containers: 
        - name: java
          image: nginx
