apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: rsset 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      color: red 
  template: 
    metadata: 
     name: javapod 
     labels:
       color: red 
    spec: 
      containers: 
        - name: java12
          image: nginx         