apiVersion: apps/v1
kind: Deployment
metadata: 
  name: java
spec: 
 replicas: 3
 selector: 
   matchLabels: 
     color: red
 template: 
   metadata:  
     name: java123 
     labels: 
      color: red 
   spec: 
    containers: 
      - name: java12
        image: nginx:1.25


