apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "firstnode"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
