aapiVersion: v1
kind: Service
metadata: 
  name: java 
spec: 
  type: ClusterIP
  selector: 
    color: red
  ports:
   - port: 80
     targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: java1
  labels:
    color: red
spec:
 containers: 
   - name: java
     image: nginx 
---        
           