apiVersion: v1
kind: Pod
metadata:
 name: hello
 labels: 
  color: black
spec: 
 containers:
  - name: nginx
    image: nginx  
--- 
apiVersion: v1
kind: Service
metadata: 
  name: ser 
spec: 
 type: ClusterIP
 selector: 
   color: black 
 ports: 
  - protocol: TCP
    port: 80
    targetPort: 80   

