apiVersion: v1
kind: Pod
metadata: 
 name: java12
spec: 
 containers: 
   - name: java12 
     image: nginx 
     resources:  
       requests: 
         memory: "128mi"
         cpu: "100m" 
       limits: 
         memory: "210mi" 
         cpu: "124m" 
         