apiVersion: v1
kind: Pod
metadata: 
  name: javawebapp
  labels: 
    color: white
spec:
 containers:    
   - name: nginx
     image: nginx
---
apiVersion: v1
kind: Service
metadata: 
  name: service12
  labels: 
    name: jaava12
spec: 
  selector: 
    color: white 
  ports: 
   - protocol: TCP 
     port: 80
     targetPort: 80
  type: NodePort              