apiVersion: v1
kind: Pod
metadata: 
  name: java12
spec: 
 containers: 
   - name: nginx
     image: nginx 
     resources: 
       requests: 
         memory: "128Mi"
         cpu: "100m" 
       limits: 
         memory: "150Mi" 
         cpu: "110m"    