apiVersion: v1
kind: Pod
metadata: 
  name: helllo
  labels: 
    color: bl-green
spec: 
 containers: 
   - name: nginx
     image: nginx 
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: service2 
spec: 
  selector: 
    color: bl-green 
  ports: 
   - protocol: TCP 
     port: 80
     targetPort: 80
  type: LoadBalancer                 