apiVersion: v1
kind: Pod
metadata: 
  name: java123
spec: 
 containers: 
   - name: nginx
     image: nginx 
     resources: 
       requests: 
         memory: "128Mi"
         cpu: "100m"
       limits: 
         memory: "210Mi"
         cpu: "120m"      